### ISSUE TITLE
PandasRollingOLS does not actually work with use_const=False

### ISSUE THREAD

**Issue by prd1** [bsolomon1124/pyfinance#6]
Even if you pass in use_const=False, the regression still appends and uses a constant.  Tried tinkering to fix this but ran into dimensionality issues - some help would be appreciated.

**Comment by prd1** [comment]
example: 

```python
from pyfinance import ols
import pandas as pd
import numpy as np
X = pd.DataFrame(index=list(range(5)), data=list(range(5)), columns=['X'])
Y = pd.DataFrame(index=list(range(5)), data=list(np.arange(0,10,2)+1), columns=['Y'])
window = 2
reg_df = pd.concat([Y, X],axis=1)
rolling_reg = ols.PandasRollingOLS(y=reg_df.iloc[:,0],  # Series
                                   x=reg_df.iloc[:,1:],  # DataFrame
                                   window=window,
                                   has_const=False,
                                   use_const=False,
                                   names=['Const','X'])
print(rolling_reg.beta)
```

output: 

```
   Const    X
1    1.0  2.0
2    1.0  2.0
3    1.0  2.0
4    1.0  2.0
```

if you try to run without specifying a name for the constant in "names" parameter:
`ValueError: Shape of passed values is (2, 4), indices imply (1, 4)`

**Comment by bsolomon1124** [comment]
Thank you for catching this @prd1 and I'm sorry it's taken me so long to have a look.  Hopefully better late than never.  It seems to be a legitimate bug.  The signature for `ols._clean_xy()` is:

```python
def _clean_xy(y, x=None, has_const=False, use_const=True):
```

However, in `ols.RollingOLS.__init__()`, it gets called just as:

```python
    def __init__(self, y, x=None, has_const=False, use_const=True):
        self.x, self.y, self.k = _clean_xy(y, x)
```

Noticeably leaving the other two parameters unpassed and so ignoring them.

I'll make a correction, push the updated changes and post a new package version on PyPI.

**Comment by bsolomon1124** [comment]
Closed via 5d07d1ec67f312ca914651668129299503e8cedd and 4d7d7b51d38361a86271616f953ee49a606d711a - please let me know if that doesn't clear everything up @prd1.  These changes are reflected on PyPI as well.

**Comment by prd1** [comment]
Hi Brad.  Sorry still having a couple issues with constants.  Using 1.2.1.


Issue1:
```
from pyfinance import ols
import pandas as pd
import numpy as np
X = pd.DataFrame(index=list(range(5)), data=list(range(5)), columns=['X'])
X.loc[:,'Const'] = 1
Y = pd.DataFrame(index=list(range(5)), data=list(np.arange(0,10,2)+1), columns=['Y'])
reg_df = pd.concat([Y, X],axis=1)
rolling_reg = ols.OLS(y=reg_df.iloc[:,0],  # Series
                                   x=reg_df.iloc[:,1:],  # DataFrame
                                   has_const=False,
                                   use_const=True,
                     )
print(rolling_reg.beta)
```


returns: `ValueError: data already contains a constant`
As it should.  But, executing the same code with has_const = True returns:
`ValueError: Data does not contain a constant; specify has_const=False`



Issue 2: (I think)

```
from pyfinance import ols
import pandas as pd
import numpy as np
X = pd.DataFrame(index=list(range(5)), data=list(range(5)), columns=['X'])
# X.loc[:,'Const'] = 1
Y = pd.DataFrame(index=list(range(5)), data=list(np.arange(0,10,2)+1), columns=['Y'])
reg_df = pd.concat([Y, X],axis=1)
rolling_reg = ols.OLS(y=reg_df.iloc[:,0],  # Series
                                   x=reg_df.iloc[:,1:],  # DataFrame
                                   has_const=False,
                                   use_const=True,
                     )
print(rolling_reg.beta)
```


Above does not add a constant.  Is it supposed to?


Currently, adding the constant manually and specifying has_const and use_cost both as False will give the desired result with constant.

**Comment by bsolomon1124** [comment]
Hi @prd1, thanks for bearing with me here.  I've made a few more commits with minor fixes and tests that should correct the issues you pointed out here, too.  Current version is 1.2.2 and the commits are 6de1db1 and 5046dd9.  Please let me know if this clears everything up, and I'll leave things open til then.  Using `pip install --upgrade pyfinance` should give you the latest version.

**Comment by prd1** [comment]
Looks good Brad.  Thank you.  I really like the rolling functionality - didn't think it was possible to make it this fast!
